Crown-Commercial-Service/ccs-scale-cat-service

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerOAuth2Config.java

Not 100% convinced this is going to solve the issue Sabarish is having (again, this afternoon) - but it might, based on the errors I've seen and reading around it (the logs show a mime-type error from the web client when processing the response from Jaggaer in the `UserProfileService` class, which seems to relate to the handling of the `application/json; charset=UTF-8` Content-type).

Add default Accept/charset headers to Jaggaer web client

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerOAuth2Config.java
src/main/resources/application.yml

Logs the request / response events from the WebClient - set the log level `uk.gov.crowncommercial.dts.scale.cat: TRACE` to see it in action - hoping we can override that via the env vars in INT, restart the app and see what's going on 🤞

WebClient logging request/response

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerAPIConfig.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/ProjectTeam.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/User.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
src/main/resources/application.yml
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java

Default behaviour is to not add this, at least for now (driven by `config.external.jaggaer.addDivisionToProjectTeam` env var) as everyone in CCS with an account on the sales platform is in the same division.  Ideally we need to ask for a new division with just us in it for testing purposes I guess 🤔

Create project with "DIVISION" project team

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerAPIConfig.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerOAuth2Config.java
src/main/resources/application.yml

Hoping this will suffice as a workaround to the issues with Jaggaer's 401 response - but need to find a better way of testing its effectiveness than waiting 24hrs for the token to expire in my local service instance!

Filter function to normalise Jaggaer API 401 response

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerOAuth2Config.java

Small update - error on INT was back to the original problem, and I think it's because I hadn't removed the existing malformed content-type header and value.  Delving into the code, the `HttpHeaders.add` method just appends an additional value to an existing header if it exists - so in this case we need to remove it completely first 👍

Remove invalid Content-Type header and values

---

iac/modules/cat-service/main.tf
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/UserProfileService.java
src/main/resources/application.yml

SCAT-1986
Updates the user profile service to query the Sales platform self-service area, including update of project and event template IDs and direct lookup in self-service area via REST API query filter change (using self-service ID stored in SSM)
@adrianmilne This should work for you already as you have a profile on the self-service side. 
@sudhakar-reddy-konda - I will request a new profile for you

Swith to Jaggaer self-service for user profile lkp

---

iac/modules/cat-service/main.tf

https://crowncommercialservice.atlassian.net/browse/CON-1729
To permit external connections to the Tenders API, move it to the public domain with nginx IP auth in front of it.

Move Tenders API to public domain

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsControllerTest.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java

SCAT-2153 - fixes to 'pocurementID` typo to align with API fix

---

iac/environments/dev/main.tf
iac/environments/sbx1/main.tf
iac/environments/sbx2/main.tf
iac/modules/cat-service/main.tf
iac/modules/cat-service/variables.tf
iac/modules/configs/deploy-all/main.tf
iac/modules/configs/deploy-all/variables.tf
src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/ApplicationFlagsConfig.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/Constants.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GlobalErrorHandler.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java
src/main/resources/application.yml
src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsControllerTest.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsControllerTest.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersControllerTest.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/util/TendersAPIModelUtilsTest.java

When set to 'true' error details API responses will include the
exception message. Only enabled on dev and sandboxes.
Added a `devMode` flag that when set to true will return the root exception details in the error response via the API. In most cases this is currently set to return an empty string, as we don't want to expose any details in errors (and nothing more sophisticated is defined/implemented yet).
As UI devs are encountering 500/other errors when getting the pieces talking to each other - thought this might be useful to give a bit more of an immediate hint as to what the issue may be - be less frustrating for the UI devs if they have a clue what the problem may be, and less need for them to ask questions of back end devs.
Tom had the great suggestion of making configurable - so …

Added a 'devMode' application flag - to assist in development

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/AgreementsServiceAPIConfig.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/TendersDBRetryable.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/exception/TendersDBDataException.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/LotSupplier.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/Organization.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/OrganisationMapping.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ProcurementProject.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/OrganisationMappingRepo.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AgreementsService.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierService.java
src/main/resources/application.yml
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/RetryableTendersDBDelegateTest.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierServiceTest.java

https://crowncommercialservice.atlassian.net/browse/SCC-441 (supplier mappings)
https://crowncommercialservice.atlassian.net/browse/SCC-440 / https://crowncommercialservice.atlassian.net/browse/SCAT-1849 (procurement project buyer organisation)
1. Replace the temporary, hardcoded list of sales platform supplier IDs with a lookup to the Agreements Service and resolution of sales platform supplier org IDs via the new organisation mappings table.
2. Resolves the buyer organisation via the same org mapping table and sets this on the procurement project record.
No

Supplier mappings from AS and buyer org

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java

SCAT-2394
Previously could change any event type - rules state once an eventType has changed from `TBD` it cannot then be changed again. Now throws an exception if this is attempted.

SCAT-2394 - cannot update an eventType which is not TBD

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/AgreementsServiceClientConfig.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/ConclaveClientConfig.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerClientConfig.java

https://crowncommercialservice.atlassian.net/browse/SCAT-2463
According to https://webtide.com/openjdk-11-and-tls-1-3-issues/ and related Github issues - e.g. https://github.com/eclipse/jetty.project/issues/3891, one possible cause of the intermittent `EOFException` we are seeing being thrown by the webclient, particularly frequently on SIT where testers are hitting the service, is an incompatibility between Jetty on JDK 11 and TLS 1.3.
This change should disable it for all three webclient instances.

Disable TLSv1.3 for all webclients to fix EOF ex

---

pom.xml
src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsController.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsControllerTest.java

https://crowncommercialservice.atlassian.net/browse/SCAT-2325
Validate the incoming `AgreementDetails` payload based on generated classes validation annotations (provided by the updated OpenAPI spec).
Both payload properties are required, cannot be null or empty strings and validation thereafter is as follows:
`agreementId`: Must match regex pattern `RM[0-9]{4}([.][0-9]{1,2})?` e.g. `RM3808`, `RM3808.1` etc
`lotId`: Must match regex pattern `([a-zA-Z0-9]+[ ]*)+` e.g. `Lot 1`, `1` etc and be max length of 20 chars
NB: The pattern for the `agreementId` is pretty clear, was less sure about the `lotId` but this seems flexible enough for a simple alphanumeric ID..

Validate AgreementDetails plus tests

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/DocumentKey.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/model/DocumentKeyTest.java

SCAT-2303
I noticed while testing that the document upload didn't like spaces in filenames (only the download endpoint). This should fix that.

SCAT-2303 - fix to allow spaces in document upload filenames

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/Application.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/ApplicationConfig.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ValidationService.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ValidationServiceTest.java

https://crowncommercialservice.atlassian.net/browse/SCAT-3241
Validate publish endpoint `endDate` to throw a `400` if the date timer provided is not in the future.  Added a couple of tests to for the new validation service method - I have the remainder of the publish event tests on a separate branch but it includes some other refactorings that weren't quite complete.
This also introduces a `Clock` instance bean - we could extend usage of this across the codebase.  The advantage is it can then be replaced with a fixed instance for testing purposes so we're not reliant on "now".

Validate endDate on publish endpoint - must be in future

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GlobalErrorHandler.java

SCAT-3263
Uploading a file whose size exceeds limit should return a 400, not a 500 error

SCAT-3263 - added MaxUploadSizeExceededException to error handler

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ConclaveService.java

SCAT-3498 - Upper/mixed case emails result in 404 when calling Conclave getUser endpoint

SCAT-3498 - convert email to lower case before calling Conclave

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/ProcurementEventRepo.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsControllerTest.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java

SCAT-3519
Implement endpoint to return EventSummaries for all events on a Project - `/tenders/projects/{proc-id}/events`
This requires pulling data from Jaggaer and the Tenders DB.
I initially was going to implement the other way around - i.e. retrieve all events from Jaggaer in a single call (a new one - to `/esop/jint/api/public/ja/v1/rfxs?flt=rfxId==rfi_39864`) and then make individual calls to the database to retrieve the necessary data.
However, given where we are, in the interests of brevity (and not anticipating many events on a project) - and the fact that would cause merge conflicts with Sudhakars get project list code - decided to take this simpler route - which is pretty lightweight in terms of code added. Can always revisit if necessary.
**Before creating a pull request make …

SCAT-3519 - added get events for project endpoint

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/mapper/DependencyMapper.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/Conditional.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/Dependency.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/DependencyType.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/Relationships.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/Requirement.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaServiceTest.java

SCAT-3504 (bugfix to update event)
SCAT-2616 dependency mapping from AS
Test team were going to raise a bug for SCAT-3504 (adding assessmentId to the procurement event table).  I said I think it's been fixed, just not on SIT yet..
As above

Release latest to SIT

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java

SCAT-3835 - persist assessmentId on update event
SCAT-3835
Bugfix

SCAT-3835 - persist assessmentId on update event (#176)

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java

https://crowncommercialservice.atlassian.net/browse/SCAT-4059
Fixed bug whereby request was made to AS for data template for all event types, including `FCA` and `DAA` that do not have one (resulting in a `500` error).

Fix get event / type assessment bug

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AssessmentCalculationService.java

SCAT-3396 & SCAT-3534
As per ACs, adjust weighted requirement scores and total scores to retain accuracy (via double).  Round the total score to two decimal places.
Note: currently, the weighted scores are not rounded for output as they are used as-is for the overall calculation.  Need to clarify with BA whether they should be also be rounded for output or left with full scale.

Calculate score to 2 dp and adjust to number output types

---

pom.xml
src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentEntity.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentStatusEntity.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AssessmentService.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsControllerTest.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java

SCAT-4249 - bugfix - get events for project endpoint was throwing error when an FCA event was present as it was trying to retrieve details from Jaggaer (no event exists in Jaggaer for FCA events).

SCAT-4249 - fix for getting events when only in Tenders DB (e.g. FCA)

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java

SCAT-4449
Dimension Weightings should have a max of 100% across all dimensions. Calculation wasn't working correctly in case where a new dimension was added, and also spotted another issue. 

SCAT-4449 - fix to the 100% dimension weighting limit validation

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/Constants.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ProcurementEvent.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/ProjectUserMappingRepo.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java

SCAT-4484
For some users the amount of time it takes to retrieve all their projects for dashboard causes the page to fail to load, which looks like login has failed. 
This is a temporary fix to unblock until better solution is implemented. The paging solution here could be extended to resolve that issue potentially - if paging could be implemented in client.
This also adds in a fix for another issue spotted - to prevent a call being made to Jaggaer for event types that are only stored in the Tenders DB (FCA, DAA). Had to distinguish between these and assessment event event types - as not a direct 1:1 correlation now FC has been added to the assessment types.

SCAT-4484 - temporary fix for /projects performance issue (limit 5)

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java

n/a
Found an issue where if you created a requirement without first creating a dimension weighting - with a weighting of 0 (by adding/updating dimension) - got an error when trying to get the Assessment - as response is hierarchical - so all requirements need to exist within a dimension.
Also made another small change to avoid a 500 error if no includedCriteria are supplied when updating a Dimension. Not sure whether this should be a 400 - but thought being permissive maybe best for this.

Bugfix - create dimension weighting if none exists when creating a requirement

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java

Update requirement can be approached 2 ways - direct via controller, or
indirect via updateDimension. If a dimensionWeighting was created in
updateDimension - it was not visible in the assessment (think because of
JPA L1 cache). So changed way DW was persisted (via assessment).

develop -> release/int

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerService.java

CON-2338
Correctly handle Jaggaer's 'profile already exists' responses for sub and super users and throw `500` as agreed in ACs.

Handle Jaggaer profile exists scenario for super and sub users correctly

---

.travis.yml

N/A
Fix from SCAT-4915 JDK 17 updates - using non-permanent download URL for Maven (noticed last build on DEV failed because of a 404 when attempting to download Maven 3.8.5 via the mirror - switched to archives).

Fix Maven download link to a permalink from archives

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerClientConfig.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/BuyerUserDetails.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/RPAExportScheduledTask.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/UserProfileService.java
src/main/resources/application.yml

SCAT-4842
Follow up changes to get self-service buyers from Jaggaer, filter by SSO and contents of local table for RPA export.  Also switches the config of the Jaggaer webclient to the `AuthorizedClientServiceOAuth2AuthorizedClientManager` rather than the default impl which only works in the context of a HTTP request, therefore making it impossible to use from scheduled components.
**N.B**
Attempted to password-encrypt the workbook, but something not right with code - it works, and exported file is password protected but for some reason Excel cannot open it (prompts for password but then complains about file format).
I will try to revisit it - it's probably not far off but examples are not that clear on how to encrypt the workbook from memory rather than from a file.
**Before creating a …

Fix S3 export, Jaggaer webclient and RPA export

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/AssessmentsController.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ValidationService.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/DocValueAdaptorsCA.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/AssessmentsControllerTest.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java

SCAT-5469 (amongst others probably)
Add a new `scores=false|true` flag to the CA `GET /assessments/{assessment-id}` endpoint, defaulting to `false` to prevent the CA calculation being hit on every request to get an assessment.

Add scores flag to GET assessments endpoint

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java

SCAT-5351
Fixes a long-standing bug whereby the internal PPG org ID was being persisted to the org mappings table rather than the scheme-identifier (as it should be - otherwise data in that table is inconsistent).

Fix conclave org-id persistence from create project

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/EncryptionService.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/EncryptionServiceTest.java

• Ideally a secure and trusted HSM should be used to generate random numbers and encryption
keys.
• For Java codebase, java.security.SecureRandom should be used.
• Generated random values should only be used once.
• Generated random values should not be exposed outside of the function or exposed to the caller
of the function.
• If the generated random value needed to be stored, then it should be handled securely and treated
the same way as a password.
Parameter values should be set to adhere to password policy recommendations. The following
recommendations for a robust password policy are derived from a combination of NCSC and CIS guidance:
Policy Setting | Minimum length 14 characters or more
Complexity     | At least 3-character sets (upper case / lower case / numbers / special …

changed code for password generation

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java

https://crowncommercialservice.atlassian.net/browse/SCAT-6758
setResponseDate now assigned wtih offsetDateTime.

responseDate now includes time attribute

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/SupplierStore.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/store/AbstractSupplierStore.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/store/DOS6SupplierStore.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/store/JaggaerSupplierStore.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/asyncprocessors/JaggaerSupplierPush.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java

https://crowncommercialservice.atlassian.net/browse/SCAT-8220
for DOS6, if the event is published before the suppliers are pushed, it ends up stored in the database. 
This change overrides the store selection and will always use Jaggaer store, when called from JaggaerSupplierPush.

JaggaerSupplierPush will always use JaggaerStore for DOS6

---

.travis.yml
src/main/java/uk/gov/crowncommercial/dts/scale/cat/auth/Authorities.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/auth/apikey/ApiKeyAuthFilter.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/auth/apikey/ApiKeyAuthManager.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/auth/apikey/ApiKeyAuthToken.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/auth/apikey/ApiKeyDetails.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/auth/apikey/ApiKeyDetailsProvider.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/auth/apikey/ConfigPropertiesApiKeyDetailsProvider.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/ApiKeyConfig.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/OAuth2Config.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersController.java
src/main/resources/application.yml
src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/EsourcingTendersControllerTest.java

EI-92
Adds an additional Spring Security based authentication mechanism for checking headers against an API key that is present in the application configuration. On successful authentication the authorities defined in the application configuration are set on the security context.

Add API key authentication

---

iac/modules/cat-service/main.tf

EI-92
Add SSM parameter to the terraform scripts to inject the API Key from the SSM Parameter Store into the environment. SSM Paramater created is "/cat/${var.environment}/auth/api-key"

Add SSM Param for ESourcing API Key to terraform

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsController.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java

https://crowncommercialservice.atlassian.net/browse/CUI-105
Adds a GET endpoint for a single project summary.  Saves us needing to use massively unperformant endpoints for simple things

Add single project summary fetch endpoint to Tenders

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GCloudAssessmentsController.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/assessment/GCloudAssessmentSummary.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/GCloudAssessmentService.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/GCloudAssessmentsControllerTest.java

https://crowncommercialservice.atlassian.net/browse/CUI-106
Adds a GET endpoint for a list of summaries of a user's GCloud Assessments. Saves us needing to spam assessment detail endpoints endlessly for basic summary info.

Add Gcloud Assessment Summaries route to Tenders

---

.github/workflows/docker-image.yml
.github/workflows/maven.yml
.github/workflows/test.yml

As we are going to move away from using Travis for the CI, make use of GitHub actions so that we can continue to test our code

Use GitHub actions to run tests for CI 

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java
src/test/java/uk/gov/crowncommercial/dts/scale/cat/util/TendersAPIModelUtilsTest.java

https://crowncommercialservice.atlassian.net/browse/GMTRP-209
Populate detail field for status codes 400, 401, 403 and 500 
No

[GMTRP-209] Populate detail field for 401, 403, 404 and 500 erro codes

---

pom.xml

Fixes the override of the managed logback-classic dependency so that it's available for the app in general use, so that AWS logging can resume.

Make logback-classic available for more than just test

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java

CUI-50
Supports the completion of assessment event types such as PA.
Currently these are just transformed back into TBD event types, but this is not sufficient to satisfy the desired flow for CUI.
Also fixes a bug in the selection of the active event - it used to just pick the first it found, now it actually picks the active event.

Added an event completion route so that assessment type events can be completed

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java

**NCAS-160:**
- If the previous question is not Monetary, which is now possible, then we need to cleanse the `minValue` variable, as the API is designed to assume this is always Monetary, when now it might not be.

NCAS-160--API-validation-fix

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java

**NCAS-346:**
- Adds validation for the number of key value pairs, submitted against Terms and Acronyms question, when saving questions and answers in the API.
Relates to: https://github.com/Crown-Commercial-Service/ccs-cas-ui/pull/715

NCAS-346--Validation-for-terms-and-acronyms

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java

**NCAS-402:**
- Fixes a parsing issue caused by using Period for invalid data format, resulting in a fallback placeholder value being used instead in the bidpack generation.

NCAS-402--Fix-parsing-error

---

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java

**NCAS-UPT:**
- Lower case passed in data type value, to ensure it matches the format in the model. So either 'String' or 'string' is valid for example.

NCAS-UPT--Sanitize-values-for-dependency-check
