.travis.yml
Same coming for the UI. Will need a PR to merge to main afterwards.
=> Deploy to INT space from main branch

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ProcurementProject.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java
Well spotted 👍 
(I'm still unsure of the wisdom / need to persist this, but it's there for now..)
=> Persist procurement project name (title)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/OAuth2Config.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsControllerTest.java
Sure this will evolve... but good for now I think.
=> Update auth roles to match fixed auth server config

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/Constants.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/AbstractRestController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GlobalErrorHandler.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/exception/MalformedJwtException.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersControllerTest.java
Merge to main for event types.
* Base data event types endpoint plus tidying
* Basic event-types endpoint tests
* Add test for malformed JWT (no sub claim)
* Tidy up
=> SCC-442 event types (#21)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/OCID.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
Little PR for a precursor change for SCC-473 👍
=> Parse and validate eventId into an OCID

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java
Updated create event call to return `EventStatus` object.
Also updated the Tenders postman collection on the `feature/CaT_Tenders_API` branch as realised it did not have the create event endpoint.
=> SCC-520 - updated response from create event to be EventStatus.

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerAPIConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerOAuth2Config.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/ProjectTeam.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/User.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java, src/main/resources/application.yml, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java
- Event status fix
- Project team (DIVISION)
- Fix Jaggaer 401 response
=> Merge to main for INT deployment

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerAPIConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/ApiError.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ProcurementProject.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/BuyerCompany.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/ExportRfxResponse.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/OwnerUser.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/ReturnCompanyData.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/ReturnCompanyInfo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/RfxSetting.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/UserProfileService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ValidationService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java, src/main/resources/application.yml, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java
As discussed, this just brings together what I've got so far towards SCC-439, plus updates to align with Dave's [changes to the API](https://github.com/Crown-Commercial-Service/ccs-scale-api-definitions/pull/66).
Bit of a mish-mash as I'd already started on the 439 changes - but hopefully nothing contentious and once merged, we can branch off integration to continue with 439 and 441 updates 👍
=> Merge to integration

.travis.yml
=> Correct develop branch name for deploy

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GlobalErrorHandler.java, src/main/resources/application.yml
=> Bump deps and tidy

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GlobalErrorHandler.java, src/main/resources/application.yml
* Bump deps and tidy
* tidy POM
=> develop -> release/int

pom.xml
=> Update Tenders API reference to point at main branch

iac/modules/cat-service/main.tf, src/main/resources/application.yml
Params added for SBX2 - will add the other envs now. Redeployed to SBX2 and all working 👍
=> Move Jaggaer URLs to SSM

iac/environments/uat/main.tf, iac/modules/cat-service/main.tf
=> hash the jar path source to detect changes

.travis.yml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/CriteriaController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/QuestionType.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/Requirement.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/RequirementGroup.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java
As discussed, does not attempt to retrieve previously answered questions from Tenders DB (for relatesTo = buyer) or Jaggaer (for relatesTo = Tenderer) - just transforms the data template requirements to Tenders API `Question`
=> Questions endpoint - basic mapping

iac/modules/cat-service/main.tf
https://crowncommercialservice.atlassian.net/browse/SCAT-2324
Inject Conclave wrapper API key from SSM into CaT API service environment
=> Inject conclave wrapper api-key

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
Remove the two 'real' hardcoded supplier IDs to avoid inadvertent communication with them via email when project is published
=> Remove hardcoded real suppliers

.travis.yml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/exception/JaggaerApplicationException.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/Rfx.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/util/TestUtils.java
=> CaT BE SIT003 16/11/2021 (Release to SIT)

.travis.yml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/exception/JaggaerApplicationException.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/Rfx.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/util/TestUtils.java
SCAT-2381 - GET/PUT project team members/owner/email recipients
=> CaT BE SIT003 16/11/2021

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
SCAT-2381
Project Owner also needs to be a Team Member
=> SCAT-2381 - adding Project Owner also adds as Team Member

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java
=> Cat BE SIT004: develop -> release/int

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java
=> SCAT-2153 - bug fix

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/AgreementsServiceClientConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/ConclaveClientConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerClientConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/Requirement.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaServiceTest.java, src/test/resources/criteria-service-test-data/criteria-buyer-multiselect.json
SCAT-2531
SCAT-2463 (Possible fix)
See JIRAs
=> Release to INT - SCAT-2531/2463

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsController.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsControllerTest.java
https://crowncommercialservice.atlassian.net/wiki/spaces/SCALE/pages/3138060313/CaT+BE+SIT005+26+11+2021
Part of release 005
=> Release to SIT (v005.1)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/OAuth2Config.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersControllerTest.java
CON-1680
CON-1682
Add roles for jaggaer buyer and supplier.  May need revisiting once confirmation of final roles per client have been confirmed.
=> Add Jaggaer roles for LD - requires verification

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/CriteriaController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java
SCAT-2584
Currently updating a question does not return any response. According to spec it should return a Question.
Refactored slightly to return a question and moved shared code to a private method (left existing TODO comment - not worth tackling that at present - not even sure it's required, but one for another day).
=> SCAT-2584 - return Question object from PUT /question response

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/AgreementsServiceClientConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/Constants.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerClientConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerTokenResponseConverter.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AgreementsService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/WebclientWrapper.java, src/main/resources/application.yml
Related to https://crowncommercialservice.atlassian.net/browse/SCAT-2463 efforts.  Didn't solve it, but figured upgrading to latest SpringBoot version probably a good idea at this juncture.
- Upgrade SpringBoot to latest
- Resolve deprecated usages where possible
- Also upped the default timeouts for all 3 external services to 10s.  I have seen some occasional timeouts, always with Jaggaer.
=> Upgrade SpringBoot to latest and increase client timeouts

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/OAuth2Config.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GlobalErrorHandler.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/JourneysController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/exception/DataConflictException.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/StringValueResponse.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/JourneyEntity.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/JourneyRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JourneyService.java, src/main/resources/application.yml, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/JourneyServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/RetryableTendersDBDelegateTest.java
https://crowncommercialservice.atlassian.net/browse/SCAT-2608
Add the journey service endpoints to Tenders API
=> Journey Service

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GlobalErrorHandler.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/exception/UnmergedJaggaerUserException.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersControllerTest.java
CON-1680/1682
Fix issue raised by Nathan - error handling meltdown due to mismatched types. Corrected and tested in controller tests.
=> Fix profile management error handling and test

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/QuestionType.java
N/A
Text is a valid question type in Agreements Service, but is not added to CaT Service enum
=> Added 'Text' question type

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/DocumentConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerClientConfig.java, src/main/resources/application.yml
SCAT-2303/bugfix
Fix for issues Daim saw when uploading/downloading large files
=> SCAT-2303 (follow up) - fix for Tomcat/Spring upload/download limits

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java
SCAT-3132
Set updatedAt field in Tenders DB after updating data template answers
=> SCAT-3132 - updatedAt field in putQuestionOptionDetails

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerClientConfig.java
SCAT-3265
Resolve OOM errors when uploading 200MB files
=> SCAT-3265 - removed request body logging (issues large file uploads)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/JourneysController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JourneyService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-2940
Fix create journey and step not found response codes (`201` / `404` respectively)
=> SCAT-2940 - fix journeys status codes

src/main/resources/application.yml
=> SCAT-3264 - updated allowed doc upload file extensions

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerService.java
SCAT-2303
Recreated PR as easier than rebasing the old one
- [ X] No
=> SCAT-2303 - added error handling to upload document

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GlobalErrorHandler.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/Requirement.java
=> SCAT-3297 sending bad request when question update data is invalid

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/QuestionType.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AgreementsService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaServiceTest.java
=> Compile error fixes after API changes

src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/AssessmentSelectionRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RequirementTaxonRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AssessmentService.java
=> SCAT-2918 - WIP on POST adding requirements

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
=> fix compiler errors (remove S3 reference)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentDimensionWeighting.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentEntity.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentSubmissionType.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentTool.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/SubmissionType.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/AssessmentTaxonRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RequirementTaxonRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AssessmentService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/AssessmentsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/RetryableTendersDBDelegateTest.java
=> SCAT-2918 - Updates to assessment endpoints (WIP)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/SubmissionTypeRepo.java
=> SCAT-2918 - addes submission type repo

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/AssessmentsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentEntity.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentStatus.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AssessmentService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/AssessmentsControllerTest.java
=> SCAT-2918 - extending AssessmentController tests

pom.xml
=> SCAT-2918 - reset assessments API to master in pom.xml

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentResult.java
=> Bugfix - changed type of supplier_organisation_id to string

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentResult.java
=> Bugfix - changed type of supplier_organisation_id to string (#167)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ProcurementEvent.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AssessmentService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
https://crowncommercialservice.atlassian.net/browse/SCAT-3501
Update the functionality of the existing `POST  /tenders/projects/{proc-id}/events` endpoint to accommodate the assessment event types `FCA` and `DAA`
=> POST Create Assessment Event

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/AssessmentsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ProcurementEvent.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentSelection.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentTool.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/DimensionEntity.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/AssessmentSelectionRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/DimensionRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RequirementTaxonRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AssessmentService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
=> Release latest CA features to SIT

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
=> CA - added check for existence of existing assessment on an event

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
=> SCAT-3835 - persist assessmentId on update event

iac/environments/dev/backend.tf, iac/environments/int/backend.tf, iac/environments/nft/backend.tf, iac/environments/sbx1/backend.tf, iac/environments/uat/backend.tf
=> Bugix - fix for TF aws provider ec2 metadata error in v 4.0 (revert)

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/Timestamps.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentDimensionWeighting.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentEntity.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentResult.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentSelectionDetail.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentTool.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentToolSubmissionType.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/CalculationBase.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/SupplierSubmission.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/AssessmentResultRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/readonly/CalculationBaseRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/readonly/ReadOnlyRepository.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AssessmentCalculationService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AssessmentService.java, src/main/resources/application.yml, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/RetryableTendersDBDelegateTest.java
https://crowncommercialservice.atlassian.net/browse/SCAT-3396
Calculate and save FC capability assessment scores, plus integration and use of new M:M relationship between `AssessmentDimensionWeighting` and `AssessmentToolSubmissionType` as scoped last week.
The following JSON can be used to create a 3-dimension multi requirement assessment for testing:
```
{
"external-tool-id": "1",
"dimensionRequirements": [
{
"dimension-id": 1,
"name": "Resource Quantity",
"weighting": 40,
"includedCriteria": [
{
"criterion-id": "0"
},
{
"criterion-id": "1"
}
],
"requirements": [
{
"name": "Data Analyst",
"requirement-id": 80,
"weighting": 60,
"values": [
{
"criterion-id": "0",
"value": "1: Less than 3"
},
{
"criterion-id": "1",
"value": "0: None"
}
]
},
{
"name": "Data Engineer",
"requirement-id": 81, …
```
=> FC CA Calculation Scores

iac/environments/int/main.tf
Enable API error messages in INT to assist testers troubleshooting
=> Enabled dev mode in INT to give useful error messages to testers

iac/environments/dev/backend.tf, iac/environments/int/backend.tf, iac/environments/int/main.tf, iac/environments/nft/backend.tf, iac/environments/sbx1/backend.tf, iac/environments/sbx2/backend.tf, iac/environments/uat/backend.tf, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/Timestamps.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentDimensionWeighting.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentEntity.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentResult.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentSelectionDetail.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentTaxon.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentTool.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentToolSubmissionType.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/CalculationBase.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/SupplierSubmission.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/AssessmentResultRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/readonly/CalculationBaseRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/readonly/ReadOnlyRepository.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AssessmentCalculationService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AssessmentService.java, src/main/resources/application.yml, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/RetryableTendersDBDelegateTest.java
- SCAT-3396 (CA Calc)
- SCAT-3225 (CA taxon traversal)
- Bugfix: AWS TF Provider issue
- Enable development mode on SIT (INT)
As above
=> Release latest to SIT

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
=> Release fix for SCAT-4059 to SIT

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentTaxon.java
N/A
@tommyb82's fix for error discovered following extended dimensions data load
=> AssessmentTaxon parent EqualsAndHashCode.Exclude fix (by @tommyb82)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentDimensionWeighting.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentSelectionDetail.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentTool.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/DimensionEntity.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/DimensionSubmissionType.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/SupplierSubmission.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AssessmentCalculationService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AssessmentService.java
The relationship needed to link to Dimension as these submission
types/criteria should be dimension specific, not tool specific.
=> Changed assessment_submission_types to dimension_submission_types.

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AssessmentService.java
Small PR to align with the API update PR after that gets merged into `master` (this morning after notifying the UI guys)
=> Align with API v0.0.2 (option-id name changed to requirement-id)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/RequirementEntity.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AssessmentService.java
=> SCAT-3225 - added groupRequirement flag

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AssessmentService.java
SCAT-3231 - noticed that DimensionSubmissionTypes were only set from includedCriteria on a create action. Should also be set during a dimension update action (to enable/disable criteria on a Dimension)
=> SCAT-3231 - set dimensionSubmissionTypes on update (as well as create)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ProjectUserMapping.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/ProjectUserMappingRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenValueAdaptors.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/RetryableTendersDBDelegateTest.java
=> SCAT-4252- project user mapping implementation

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/AssessmentsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/CalculationBase.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ValidationService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentCalculationService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/CAException.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/CalculationAdaptor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/PricingCalculator.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/StandardWeightedCalculator.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/AssessmentsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ValidationServiceTest.java
https://crowncommercialservice.atlassian.net/browse/SCAT-3534
DA calculation i.e. Pricing tool. See JIRA for details..
=> Pricing (DA) calc

src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/ProjectUserMappingRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java
=> SCAT-2136 use of project user mapping table

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentDimensionWeighting.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentEntity.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentSelection.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentTaxon.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/DimensionEntity.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/RequirementEntity.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java
SCAT-3131 (extended)
Added logic to implement overwrite requirements flag
Also added `@Transactional` and set a number of relationships to `LAZY` loading.
Note: will update `pom.xml` following merge of PR in `api-definitions`
=> Feature/scat 3231 overwrite requirements 

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java
=> Added validation to check dimension weighting falls within range

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/RfxSetting.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java
=> SCAT-2136 - publish and end dates added to active event

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
SCAT-4431
Added some validation fixes to check for nulls when creating an Assessment
Also added code to populate suppliers for an FCA/DAA event (was missing).
=> SCAT-4431 - extra CA validation and add suppliers to CA event

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerAPIConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/MessageController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/AttachmentList.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/Message.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/MessageList.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/MessageRequestInfo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/MessagesResponse.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/ReaderCompany.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/Reading.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/ReadingList.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/Receiver.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/ReceiverList.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/Sender.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/SenderUser.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/resources/application.yml, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/MessageControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
=> WIP: SCAT-3090 - get messages from suppliers

iac/modules/cat-service/main.tf
https://crowncommercialservice.atlassian.net/browse/SCAT-4439
Inject required RPA encryption params
=> Inject RPA params

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/AssessmentsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java
SCAT-4438 - added extra validation to check you cannot add a requirement from one dimension on a different dimension
=> SCAT-4438 - added extra validation around requirements

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java
=> SCAT-3090 returning empty message summary when no messages found

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java
Resolved "Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/boot/configurationprocessor/json/JSONObject" in dev environment
=> resolved jsonobject error in dev env

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-3805
Modify the check on request property `OCDS.title` to check null/empty string case - empty (blank) strings were slipping through and causing Jaggaer to throw an exception.
=> Fix event title value check - null or blank

src/main/resources/application.yml
=> SCAT-3090 added missing get message url

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/MessageControllerTest.java
=> SCAT-3090 Api changes

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/Constants.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ProcurementEvent.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ValidationService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ValidationServiceTest.java
SCAT-3817
Simplify the `is assessment event` logic and bit and rejig the validation checks to align better with ACs.
=> Rejig update event / assessment event logic

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java
=> SCAT-3622 fix for Author mapping

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentCalculationService.java
SCAT-3787
Fix build issues from recent API changes
=> Fix compilation problems from API changes

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/Constants.java
SCAT-3820
Create Assessment for FC event types
=> SCAT-3820 - added FC to list of ASSESSMENT_EVENT_TYPES

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/Constants.java
SCAT-3820
Add `FC` to assessment event types
=> SCAT-3820 - added FC to list of ASSESSMENT_EVENT_TYPES (#230)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
=> SCAT-4582 - added null check

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
SCAT-4484
Added some extra logging to troubleshoot an issue. 
Fixed Sonar warning (used method reference)
Formatted
=> SCAT-4484 - added logging for troubleshooting issue

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
=> SCAT-4572 Handling to RFX not found from jaggaer

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java
SCAT-4476
Previous validation to check if a requirement was valid for a dimension only considered top level of assessment taxon tree. This failed for dimension 7 as there are sub levels. Extended the check to be recursive and walk down whole tree looking for a matching requirement
=> SCAT-4476 - enhanced validation to check if requirement is in dimension

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/TendersS3ClientConfig.java
=> Fix hardcoded reference to SBX2 bucket service

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ProcurementProject.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
Fix off the back of SCAT-2642
We need a functional integration/regression test suite.... 😞 
=> Add ToString.Exclude and Transactional

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ProcurementProject.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
Add ToString.Exclude and Transactional (#245)
=> Release latest to SIT (bugfix SCAT-2642)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerAPIConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerSOAPAPIConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerSOAPClientConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/SubUsers.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/UpdateSubUserSSO.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/UpdateSuperUserSSO.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerSOAPService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/UserProfileService.java, src/main/resources/application.yml, src/main/resources/jaggaer-soap/UpdateSubUserSSO.xml, src/main/resources/jaggaer-soap/UpdateSuperUserSSO.xml, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementServiceTest.java
CON-1680
CON-1682
Workaround for the SSO data bug via Jaggaer REST API, by using the SOAP API to add that data instead.  Plus some hardcoded fixes to get the buyer self-service sub user creation working again.
=> SSO data via SOAP API + bugfix buer creation

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerAPIConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/RfxWorkflowRequest.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/WorkflowRfxResponse.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/RPAGenericService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierService.java, src/main/resources/application.yml, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierServiceTest.java
=> added start evaluation code

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/documentupload/DocumentUploadService.java, src/main/resources/application.yml, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
CON-1680 (LD fix for retrieving user profiles - was not returning SSO data for supplier sub-users previously)
SCAT-4619 - Need Nick approval for duplicate file fix (included here - see comment on ticket)
A above
=> Few fixes for DUS and LD endpoints

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/StandardWeightedCalculator.java
No JIRA
Fixed a couple of small issues discovered during testing assessment/calculation for FE guys
=> Bugfix - couple of fixes for assessment and calculation

src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsControllerTest.java
Test was failing due to switch to BST
=> Bugfix - fix to OffsetDateTime issue in test in BST

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerAPIConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ProcurementEvent.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/resources/application.yml, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java
=> SCAT-4583 performance improvements for projects

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
=> Bugfix when creating/updating event

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementServiceTest.java
https://crowncommercialservice.atlassian.net/browse/CON-2204
Fix bug in `PUT /tenders/users/:userId` (register user) roles comparison, plus unit tests.
=> Bugfix for LD Register User - conflicting roles

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/UserProfileService.java
CON-2218 (user details not updated in Jaggaer)
CON-2204, 2203 etc - follow up fix to permit registration
=> Fix for various CON defects raised by test team

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
https://crowncommercialservice.atlassian.net/browse/SCAT-4578
Project listing response for each event (`EventSummary` had incorrect external reference value and missing assessment ID when present on event (for `FCA`, `DAA`, `FC`).
=> Fixes for event summary in project listing

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageServiceTest.java
https://crowncommercialservice.atlassian.net/browse/SCAT-4644
=> added code to get org info from conclave

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/OAuth2Config.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersControllerTest.java
CON-2176
Add correct CAT LD role for authorisation
=> Add correct CAT LD role for auth and update test

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-4652
=> added condition for unclassified enum value

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java
=> SCAT-4695 duplicate options data

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
=> SCAT-4703 Updating status, publish, close dates after publishing event

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/QuestionAndAnswerController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/QuestionAndAnswer.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/QuestionAndAnswerRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/QuestionAndAnswerService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/QuestionAndAnswerServiceTest.java
=> Latest SIT Release

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ProcurementEvent.java
https://crowncommercialservice.atlassian.net/browse/SCAT-4703
=> removed updated false on dates

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
https://crowncommercialservice.atlassian.net/browse/SCAT-4705
=> added validation for weighting

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/Message.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-4668
=> added parent-id

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/Constants.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ProcurementEvent.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
=> SCAT-4250 - fix to get data template for RFI,EOI & FC event types

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
=> SCAT-4715 fix for duplicate projects

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerAPIConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/ExtendEventRfx.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/RfxRequest.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/RfxSettingRequest.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ValidationService.java, src/main/resources/application.yml, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
added extend endpoint
https://crowncommercialservice.atlassian.net/browse/SCAT-2142
=> added extend endpoint

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/MessageController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageServiceTest.java
https://crowncommercialservice.atlassian.net/browse/SCAT-4822
=> added download message attachment endpoint

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerService.java
=> Release to SIT

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/UserProfileService.java
=> Fix for multi-buyers with same email address under self-serve (#311)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java
CON-2224
CON-2346
Bug fixes as above.
=> Fixes for CON-2224+2346 (#314)

pom.xml
N/A - this is a version bump to latest SpringBoot version.
Non-functional.
=> Bump SpringBoot version to latest 2.6.7

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/Requirement.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java
=> Added missing Table definition

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/ExportRfxResponse.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/LastRound.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/SupplierResponseCounters.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
=> Fix for build failure due to API change

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java
=> SCAT-4827 bug fix

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java
https://crowncommercialservice.atlassian.net/browse/SCAT-4852
=> updated endpoint

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/Constants.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ValidationService.java
=> SCAT-3512 event updates

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-4603
=> added validation for neg numbers

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/Offer.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
=> Response Date  for the responded suppler is added

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/Offer.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
=> release to int

src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
=> changed the status for To-be_Evalated and applied trim

src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
=> changed the status for To-be_Evalated and applied trim (#349)

.travis.yml, iac/environments/pre/backend.tf, iac/environments/pre/main.tf, iac/environments/pre/variables.tf
SCAT-4912 
Non-functional - environment config only.
=> Pre-production (pre) environment configuration

.travis.yml, iac/environments/pre/backend.tf, iac/environments/pre/main.tf, iac/environments/pre/variables.tf, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ProcurementEvent.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/Offer.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
=> Release to pre-production

iac/modules/cat-service/main.tf, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/RPAAPIConfig.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierServiceTest.java
* Remove redundant rpa temp pswd config
* Remove references to env config buyer pswd
=> Bugfix/scat 4912 remove rpa temp pswd config (#359)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
=> SCAT-5114 400 error if existing not not active status to close it

iac/modules/cat-service/main.tf, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/ConclaveAPIConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/ConclaveClientConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/CompanyInfo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ConclaveService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenValueAdaptors.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java, src/main/resources/application.yml
SCAT-4579
Ensure org name is set in event suppliers listing via identities API.  Also sets the org identifier in new supplier super-user endpoints created by register user endpoint.
=> Integrate CII identities API and use to search by DUNS

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/AbstractRestController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/AssessmentsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GlobalErrorHandler.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/exception/NotSupportedException.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/SupplierSubmissionRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/AssessmentsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/RetryableTendersDBDelegateTest.java
=> SCAT-3787 -Supplier Dimension Data

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ConclaveService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
SCAT-4579
Better error logging and handling around supplier lookup from identities service.
=> Fix get suppliers to handle org not found in Conclave

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ValidationService.java
=> SCAT-5235 missing event type

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java
=> Dashboard status added for the projects endpoint

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
=> null pointer issue fixed

.travis.yml, iac/environments/prd/backend.tf, iac/environments/prd/main.tf, iac/environments/prd/variables.tf, iac/modules/cat-service/main.tf, iac/modules/cat-service/variables.tf, iac/modules/configs/deploy-all/main.tf, iac/modules/configs/deploy-all/variables.tf, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/ApplicationFlagsConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AwardService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/QuestionAndAnswerService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/UserProfileService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java, src/main/resources/application.yml, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/AwardServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/QuestionAndAnswerServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierServiceTest.java
SCAT-5025
SCAT-4998
- (Env configurable buyer user profile resolution - email or SSO).  SSO in prd.
- Production env config
- Move some CA logging to `TRACE` level only.
=> Prd config (SSO, logging, iac)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
Quick workaround for unrealistic project counts in DEV+SIT DBs
=> Limit projects recall from jaggaer to most recent 20

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
=> Latest to SIT

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/RPAServiceClientConfig.java
SCAT-4921
Enable webclient logging for RPA traffic..
=> Wire level HTTP trace for RPA

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ValidationService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ValidationServiceTest.java
=> null check removed for duration

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java
=> SCAT-4652 page total calculation fix

iac/modules/cat-service/main.tf, iac/modules/cat-service/variables.tf, pom.xml
SCAT-4915
Upgrade the Java buildpack to latest version.  I deliberately haven't updated the Java version as wanted to do that in a follow up step if this all goes through ok.  Tested on SBX2 with a variety of API calls and all working as expected.
=> Upgrade Java buildpack and make necessary adjustments

.github/workflows/codeql-analysis.yml, .travis.yml, iac/modules/cat-service/main.tf, pom.xml
SCAT-4915
Hope is to resolve issues with JDK 11 and Spring web client. Or at least eliminate that as a cause.
=> Upgrade CaS API to JDK 17

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
=> SCAT-5372 weighting check for sum of dimensions

iac/modules/cat-service/main.tf, pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/NotificationClientConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/TendersRetryable.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/UserRegistrationNotificationConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/exception/NotificationApplicationException.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/NotificationService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/NotificationServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/RetryableTendersDBDelegateTest.java, src/test/resources/application-test.yml
CON-1359
Sends an email to the configured address with configured template via GOV.UK Notify when a new buyer user is registered.
=> User registration email notification

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/documentupload/DocumentUploadService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-5317
=> changed status

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/documentupload/DocumentUploadService.java
SCAT-4915
Add some retry logic to webclient to hopefully mitigate intermittent EOF exception
=> Add retry to DUS webclient for upload

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
=>  calling start evaluation and open envelope in case we do not see any offers with tech offer  

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
=> SCAT-5434 - tender period to events summary

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentCalculationService.java
=> SCAT-5486 overwriteSuppliers flag when for POST method

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ProcurementEvent.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/SupplierSelection.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-5261
=> added copy suppliers code

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerAPIConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/SearchRfxsDataList.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/SearchRfxsResponse.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java, src/main/resources/application.yml, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java
N/A
Switch dashboard endpoint to make single call to search Rfxs based on project user's DB records.  This should dramatically improve performance 🤞 
=> Switch dashboard endpoint to use single call to Jaggaer

iac/modules/cat-service/main.tf
=> Remove RPA-S3 prefix in prd env

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/PricingCalculator.java
=> SCAT-5559 wrong comparison of suppler id

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-5572
=> terminate event code for assessment event types

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
=> SCAT-5579 hibernate initialisation error fix

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
=> SCAT-5846 adding supplier to db bug

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerAPIConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/ScoringController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/CommentData.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/EnvelopeSupplierComment.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/EnvelopeSupplierCommentList.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/EvaluationCommentList.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/ExportRfxResponse.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierService.java, src/main/resources/application.yml
https://crowncommercialservice.atlassian.net/browse/SCAT-5243
=> added getscore endpoint

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GlobalErrorHandler.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/exception/JaggaerUserExistException.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersControllerTest.java
=> Returning error in case we have Jaggaer user already exist

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/Constants.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
=> SCAT-5589 Assessment id in response for DA event

src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/readonly/CalculationBaseRepo.java
=> SCAT-5584 - changes to view

src/main/resources/application-local-pg.yml, src/main/resources/sample.local-env.yml
Environment variables configuration for local setup
=> environment variables - spring config

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/AssessmentsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java
=> New endpoint to update dimensions

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/AssessmentsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java
=> Update dimensions in bulk

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/AwardController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AwardService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-5243
=> added getawards endpoint

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/CalculationBase.java
=> changed calc id

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentCalculationService.java
=> Remove filter for suppliers

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/documentupload/DocumentUploadService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-5351
=> added default size

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
=> Added the suppliers to capability assessment suppliers

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/CalculationBase.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentCalculationService.java
=> Releasing it to SIT

src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java
https://crowncommercialservice.atlassian.net/browse/SCAT-5243
=> added preaward status

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/documentupload/DocumentUploadService.java
=> resolved doc data length error

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentCalculationService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java
=> filter supplier_id with all the required dimensions

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/resources/application.yml
=> added status and check null value for dates

iac/environments/prd/main.tf, iac/environments/pre/main.tf, iac/environments/uat/main.tf
=> changed dev mode to true

src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/AssessmentTaxonRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-5938
Assessment taxonomy filtered by dimension and assessment tool id.
=> SCAT5938: taxonomy filtered by assessmenttool id

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/UserProfileService.java
=>  implementation for the supplier information is done

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
=> updated response state for awarded suppliers

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerAPIConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/UserProfileService.java, src/main/resources/application.yml, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementServiceTest.java
https://crowncommercialservice.atlassian.net/browse/SCAT-5944
=> added check to find the jaggaer sup org

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/AssessmentsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/SupplierSubmissionData.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/readonly/SupplierSubmissionDataRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-6009
filtering based on tool id implemented
=> Assessment tool and dimensionid based filtering implemented

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/AssessmentsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/SupplierSubmissionData.java
https://crowncommercialservice.atlassian.net/browse/SCAT-6010
Added json response format for API  /assessments/tools/:toolId/dimensions/:dimensionId/data
=> added json response SCAT 6010

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/DocValueAdaptorsCA.java
https://crowncommercialservice.atlassian.net/browse/SCAT-5351
=> added template value

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/RPAExportScheduledTask.java
=> merged to pull latest source from develop

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentTool.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentToolDimension.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/DimensionEntity.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-5606
New table assessment_tool_dimension added and min, max weighting percentage is configured in the same table.
=> SCAT 5606 - new table and weighting changes

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java
=> added description for the ddat role

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentTaxon.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentToolSubmissionGroupMapping.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/DimensionEntity.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/SubmissionGroup.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/AssessmentTaxonRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/DimensionRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RequirementTaxonRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java
https://crowncommercialservice.atlassian.net/browse/SCAT-6118
Added submission group data model. Base-work to remove dependency between assessment tool and assessment taxonomy.
=> database initial changes remapped

src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/AssessmentScoreCalculator.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/AssessmentToolCalculator.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/AssessmentToolFactory.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/BaseCalculator.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/DimensionScoreCalculator.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/ExclusionPolicy.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/impl/AllNonZeroExclusionPolicy.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/impl/AtleastOneExclusionPolicy.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/impl/BasicAssessmentToolCalculator.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/impl/NoopDimensionCalculator.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/impl/NoopExclusionPolicy.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/impl/PricingDimensionCalculator.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/impl/SpringAssessmentToolFactory.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/impl/StandardWeightedAssessmentCalculator.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/impl/StandardWeightedDimensionCalculator.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentToolDimension.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersControllerTest.java
Assessment tools - modularized implementation
=> Assessment tool modularized - 2nd stage

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/Constants.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
=> Added PA status to for the MCF3 requirement

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-6172
Added @Transactional  for the service method
=> added transactional annotation

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java
=>  messages totals are updated as per filter predicates

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/Constants.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GlobalErrorHandler.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/exception/OperationNotSupportedException.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/EventTransitionService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java
=> Feature/scat 6231 complete/close/terminate initial functionality is implemented 

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/Constants.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/EventTransitionService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java
Completion logic changed for assessment types
=> SCAT-6314 - Assessment completion logic changed

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
Null check added for eventSummary
=> EventSummary null check added

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
Fixed dashboard status issue
Fixed issue with termination event
=> SCAT-6329 Fixed couple of integration issues

src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/AssessmentToolCalculator.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/impl/BasicAssessmentToolCalculator.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/impl/SpringAssessmentToolFactory.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java
Persist calculation results to the database
=> calculations persisted to assessment_results

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java
https://crowncommercialservice.atlassian.net/browse/SCAT-6329
added assessmentId in response
=> added assessmentId in response

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-6402
=> changed code for responses state

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
NullPointer fixed while checking tender status
=> null pointer exception fixed

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-4571
=> condition for unclassified classification

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-4571
=> updated code for unclassified

src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/CalculationParams.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/DimensionScoreCalculator.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/impl/BasicAssessmentToolCalculator.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/impl/NoopDimensionCalculator.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/impl/PricingDimensionCalculator.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/impl/ScoreUtil.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/impl/SpringAssessmentToolFactory.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/impl/StandardDimensionCalculator.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/impl/StandardSupplierSubContractorDimensionCalculator.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/assessment/ValueCount.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/readonly/SupplierSubmissionDataRepo.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/assessment/StandardDimensionCalculatorTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/assessment/StandardSupplierSubContractorDimensionCalculatorTest.java
https://crowncommercialservice.atlassian.net/browse/SCAT-6161
=> Supplier-subcontractor support implemented

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenValueAdaptors.java
https://crowncommercialservice.atlassian.net/browse/SCAT-6206
=> updated eoi template data

src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/DocumentUploadRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/documentupload/DocumentUploadService.java
=> temporary fix for s3 doc issue

src/main/java/uk/gov/crowncommercial/dts/scale/cat/assessment/impl/BasicAssessmentToolCalculator.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/AssessmentDimensionCriteria.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/AssessmentDimensionCriteriaRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentDimensionCriteriaService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-6161
per-requisite for 616subcontractor option added - SCAT-6135
=> implementation for supplier-subcontractor support

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/QuestionAndAnswerController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/QuestionAndAnswerService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/QuestionAndAnswerServiceTest.java
https://crowncommercialservice.atlassian.net/browse/SCAT-6487
=> get QA code changes

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/QuestionAndAnswerService.java
=> added valid check

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java
=> Fixed issue project/{events}/events endpoint

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
https://crowncommercialservice.atlassian.net/browse/SCAT-6665
=> added check for assessment tool id is null

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-6054
=> Added attribute to return the file size

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-6564
=> Fix the scenarios of SCAT-6566 and SCAT-6564

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/GCloudAssessmentService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/documentupload/DocumentUploadService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java
=>  performance fixes 1

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java
=> Feature/scat 8888 reverted fix 

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-4431
=> Throwing validation error when there is a nullpointer

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/QuestionAndAnswerService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/RPAGenericService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/AwardServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierServiceTest.java
=> Fixed few more endpoints for fixing RFX performance issue

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/AgreementsServiceClientConfig.java
=> added codec size for webclient

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/AssessmentsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/AwardController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/ContractController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/CriteriaController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/DocumentTemplatesController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GCloudAssessmentsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/JourneysController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/MessageController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/QuestionAndAnswerController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/ScoringController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/interceptors/ExecutionTimeAdvice.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/interceptors/TrackExecutionTime.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/documentupload/DocumentUploadService.java
=> Feature/scat 6766 performance fixes to nft 

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/RPAExportScheduledTask.java
https://crowncommercialservice.atlassian.net/browse/SCAT-4842
=> changed excel content format

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/resources/application.yml
=>  hikari pool increased to 30

src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/ProcurementEventHelperService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/helper/ProcurementEventHelperServiceImpl.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/RequirementGroupAsIsProcessor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/RequirementGroupEditProcessor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/RequirementGroupPartProcessor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaServiceTest.java
https://crowncommercialservice.atlassian.net/browse/SCAT-6047
Added processing of the data-template
validation of AsIs question to be not updated.
Set Values, only if old-data has value available.
=> data merging and checks on updates

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
=> removed add info

src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/TwoStageEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/OrganisationMappingRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-5956
For FC2FC events, copy supplier from jaggaer and mark the 1st event as closed
=> Copy supplier from prev fc and mark CLOSED

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
=> Jaggaer is giving an issue for addition info

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GlobalErrorHandler.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/exception/JaggaerUserNotExistException.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-6033
=> Changed error to throw 400 when user is not found in Jagger

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
=> added check for empty projects

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ConclaveService.java
=> Made changes to use same identity endpoint to get the buyer name

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/ConclaveAPIConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/ConclaveClientConfig.java, src/main/resources/application.yml
=> changed cci base url

iac/modules/cat-service/main.tf
=> added aws config

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java
=> Filtering the users with no RightProfile

.travis.yml
=> corrected indentation for release/nft branch

src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/DocumentTemplateRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocumentTemplateService.java
=> updated code for dos6 template

src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocumentTemplateService.java
=> updated code for doc

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/Requirement.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java
=> answered field updates from the request

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/documentupload/DocumentUploadService.java
=> revert description changes

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java
=> Replacing budget with Not applicable

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/Requirement.java
=> added ignore properties SCAT-7233

src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/SupplierStore.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/SupplierStoreFactory.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/store/AbstractSupplierStore.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/store/DOS6SupplierStore.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/store/DatabaseSupplierStore.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/store/JaggaerSupplierStore.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
https://crowncommercialservice.atlassian.net/browse/SCAT-7247
changed to factory pattern for supplier store to handle Jaggaer / Database persistence for suppliers.
=> DOS6 FC supplier store by publishdate

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/RPAExportScheduledTask.java
https://crowncommercialservice.atlassian.net/browse/SCAT-4842
Final fix
=> added static phone number

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java
=> Capturing the value selected

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java
=> Reverted the fix

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-6628
Assessment Id should not be set as NULL 
=> null assessmentId  not to be updated in database

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java
=> Added new method to return all the strings as comma seprated value

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java
=> Currency converstion changes

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java
=> Triming the whitespaces

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java
=> Adding the exact field name

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java
=> Releasing to SIT

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java
=> Release to UAT

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java
=> Release to NFT

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GCloudAssessmentsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/AssessmentRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/GCloudAssessmentRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/projection/AssessmentProjection.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java
=> Endpoint rewritten to improve performance

src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/GCloudAssessmentService.java
=>  GCloud create and update functionality revisited

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java
=> Added the condition to exclude the not applicable values

src/main/resources/application.yml
=> jaggaer time out updated

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierService.java
=> added end evaluation check

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java
=> Issue with String during publish

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java
=> Releasing to INT

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java
=> Added fix to remove whitespace

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java
=> release int

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java
=> Removed unwanted code

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/ApplicationFlagsConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/SupplierStore.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/AsyncConsumer.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/AsyncExecutor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/RetryableException.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/queueExecutor/AsyncExecutionConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/queueExecutor/BlockCallerExecutionPolicy.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/queueExecutor/QueuedAsyncExecutor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/queueExecutor/RunnableTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/queueExecutor/Task.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/store/JaggaerSupplierStore.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/EventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/asyncprocessors/JaggaerSupplierEventData.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/asyncprocessors/JaggaerSupplierPush.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
https://crowncommercialservice.atlassian.net/browse/SCAT-7885
Async Execution of Jaggaer supplier push on create Event/Project
=> Async execution of Jaggaer Supplier push on create event

src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/SupplierStore.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/queueExecutor/RunnableTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/store/AbstractSupplierStore.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/store/DOS6SupplierStore.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/store/DatabaseSupplierStore.java
DOS6 stage 2 FC event handling with Asynchronous push.
=> DOS6 stage 2 FC event handling fixed

src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/queueExecutor/TaskDataStoreRefresher.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/TaskRepo.java
Changed from 5 mins interval to 15 mins delay to accommodate on-going process.
=> DataStore schedule changed to 15 mins delay

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/QuestionAndAnswerService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-7517
=> added of condition to check the jaggaer status

src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/specification/ProjectSearchSpecification.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
=>  added case insensitive search

src/main/resources/application.yml
=> Jaggaer timeout increased to 300 seconds

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerAPIConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/MessageUpdate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/OperatorUser.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java, src/main/resources/application.yml
=> Changes to mark message as read

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java
=> Added the read fix

.gitignore, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GlobalErrorHandler.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementServiceTest.java
reverted SCAT-7941 jaggaer user tickets and added con-3389
=> Feature/con 3389 duns validation (#959)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
=> reverted deleted filed

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java
https://crowncommercialservice.atlassian.net/browse/CON-3425
=> code changes to update DUNs number in jaggaer

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenService.java
=> Fixing notSpecified issue

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerService.java
=> Update call is changed to Async

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
=> condition updated

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerService.java
=> Moving 8464 fix to Preprod

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-8467
=> moved if condition in update scores

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-8514
=> added start evaluation api

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/asyncprocessors/JaggaerSupplierPush.java
https://crowncommercialservice.atlassian.net/browse/SCAT-8220
Throwback Jaggaer error, if retry is not required
=> Throw jaggaer error if error code is not -998

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-8514
=> added if condition for dos6

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/OrganisationMapping.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/OrganisationMappingRepo.java
https://crowncommercialservice.atlassian.net/browse/SCAT-7936
=> bravo id selection based on the primary flag

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ConclaveService.java
=> Added the sanitization on the Duns Number

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/OrganisationMapping.java
(https://crowncommercialservice.atlassian.net/browse/SCAT-7936)
Data type changed to primitive type because its a not null constraint in DB.
=> Org mapping data type change

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-8250
removal of suppliers in publish-refresh-suppliers implemented.
=> removal of suppliers on publish-refreshsuppliers added

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerService.java
=> added comment for build failure changes

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
https://crowncommercialservice.atlassian.net/browse/SCAT-8599
=> uncommented rfx additional data

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/OrganisationMapping.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/store/AbstractSupplierStore.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/store/DatabaseSupplierStore.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/store/JaggaerSupplierStore.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/OrganisationMappingRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AwardService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/AwardServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierServiceTest.java
https://crowncommercialservice.atlassian.net/browse/SCAT-8618
Changes to add additional column in Org Mapping table.
=> additional column in org_mapping table and associated file changes

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java
https://crowncommercialservice.atlassian.net/browse/CAS-178
=> OR condition for orgmapping finding

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/GCloudAssessmentService.java
https://crowncommercialservice.atlassian.net/browse/CAS-447
removed empty result validation on querying assessment details
=> empty result validation removed on query

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/GCloudAssessmentService.java
=> Merging the cas-447 specially to Int

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/ConclaveAPIConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java, src/main/resources/application.yml
https://crowncommercialservice.atlassian.net/browse/CAS-444
=> added CAT_User role for buyer creation

iac/modules/cat-service/main.tf, pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GlobalErrorHandler.java, src/main/resources/application.yml, src/main/resources/logback-spring.xml
https://crowncommercialservice.atlassian.net/browse/CAS-532
=> Integrated rollbar

src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/specification/ProjectSearchSpecification.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/resources/application.yml, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java
https://crowncommercialservice.atlassian.net/browse/CAS-87
=> added filter for get projects based on event date

src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/specification/ProjectSearchSpecification.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AwardService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierService.java, src/main/resources/application.yml, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/AwardServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java
Revert "Feature/cas 87 sort projects (#1091)"
=> release/nft after Feature/cas 87 revert

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/OAuth2Config.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/QuestionAndAnswerSupplierController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/QuestionAndAnswerService.java
https://crowncommercialservice.atlassian.net/browse/CAS-1066
=> created supplier QandA public api

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java
https://crowncommercialservice.atlassian.net/browse/CAS-87
=> added date to get events

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java
https://crowncommercialservice.atlassian.net/browse/CAS-1048
=> usergroups check for roles

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersController.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersControllerTest.java
=> Added the response when the user already exists

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java
https://crowncommercialservice.atlassian.net/browse/CAS-1046
=> added buyer check for duns updation in jaggaer

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersController.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersControllerTest.java
=> Reverting the change

iac/modules/cat-service/main.tf, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerAPIConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/OAuth2Config.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java, src/main/resources/application.yml, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsControllerTest.java
https://crowncommercialservice.atlassian.net/browse/EI-98?atlOrigin=eyJpIjoiOGY1Y2E0YjhiNGNiNGJmOWE1Nzc1NDlhYmEzMDU1YmYiLCJwIjoiaiJ9
Update to the /termination endpoint to allow the endpoint to be called with API Key or Conclave auth token.
- [ x] No
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)
=> EI-98 Update existing /termination endpoint in CATS for eSourcing

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementServiceTest.java
https://crowncommercialservice.atlassian.net/browse/CAS-665
=> check supplier link while supplier enrollment

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/ConclaveAPIConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java, src/main/resources/application.yml
https://crowncommercialservice.atlassian.net/browse/CAS-444
=> cas-44 changes back to dev

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/SupplierLinkEntity.java
https://crowncommercialservice.atlassian.net/browse/CAS-664
=> id column added

src/main/resources/logback-spring.xml
=> added console log

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/Constants.java
=> Added complete status

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/Constants.java
=> Release branch for INT

codeclimate.yml
Adding CodeClimate YML config file to support CodeClimate analysis being added to PRs going forward
=> Add CodeClimate config to support CodeClimate analysis

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersControllerTest.java
=> Added the fix Back

src/main/java/uk/gov/crowncommercial/dts/scale/cat/exception/SSOObjectMissingException.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java
=> Throwing exception when sso is not present

.github/dependabot.yml
[CAS-1251](https://crowncommercialservice.atlassian.net/browse/CAS-1251)
Dependabot will run once a week every Sunday to fetch the latest updates.
It will be able to open a maximum of 5 PRs.
[CAS-1251]: https://crowncommercialservice.atlassian.net/browse/CAS-1251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CAS-1251 - Add the dependabot config

.github/dependabot.yml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java
https://crowncommercialservice.atlassian.net/browse/CAS-1241
=> added code to delete email recipients

src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/ProcurementEventRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
https://crowncommercialservice.atlassian.net/browse/EI-97?atlOrigin=eyJpIjoiMWZjYThhNzg4ZTRmNGY1YWFjNDgwZjMyNzBmNTdlN2UiLCJwIjoiaiJ9
- update to filter only environment relevant procurement events
- fix to event id and procurement id to return the correct id's for Salesforce
- [x ] No
=> Ei-97 Add /deltas endpoint to CAT Service

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java
https://crowncommercialservice.atlassian.net/browse/CAS-1241
=> deleting memeer in localdb

src/main/java/uk/gov/crowncommercial/dts/scale/cat/JaggaerSupplierDownloader.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/SupplierProcessor.java
=> coh checking and special code removal

.travis.yml
Remove the requirements that branches need a certain name to run travis
=> Remove the requirements that branches need a certain name to run travis

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/TaskEntity.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/TaskHistoryEntity.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/AsyncConsumer.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/AsyncMultiConsumer.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/ErrorHandler.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/NoopErrorHandler.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/TaskConsumer.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/queueExecutor/QueuedAsyncExecutor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/queueExecutor/Task.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/queueExecutor/TaskEntityService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/queueExecutor/TaskRunner.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenValueAdaptors.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/asyncprocessors/ErrorHandlers.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/asyncprocessors/JaggaerErrorHandler.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/asyncprocessors/JaggaerEventPublish.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/asyncprocessors/JaggaerSupplierPush.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/asyncprocessors/input/JaggaerPublishEventData.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/asyncprocessors/jaggaer/DocumentPushTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/asyncprocessors/jaggaer/EventPublishTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/asyncprocessors/jaggaer/PublishPrevalidationTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/asyncprocessors/jaggaer/SupplierPushTask.java
=> Async publish API initial implementation

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/MessageTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/MessageTaskStatus.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/MessageTaskRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java
=> Repo and entity

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/TaskEntity.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/TaskGroupEntity.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/TaskScheduler.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/queueExecutor/AsyncExecutionConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/queueExecutor/QueuedAsyncExecutor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/queueExecutor/RunnableTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/queueExecutor/Task.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/queueExecutor/TaskDataStoreRefresher.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/queueExecutor/TaskEntityService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/queueExecutor/TaskRetryManager.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/async/queueExecutor/TaskRunner.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/MessageTaskRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/TaskGroupRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/RetryableTendersDBDelegateTest.java
https://crowncommercialservice.atlassian.net/browse/CAS-1112
=> three times retry implemented

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/MessageController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/MessageAsync.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/MessageTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/MessageTaskRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/asyncprocessors/JaggaerMessagePush.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/asyncprocessors/input/MessageTaskData.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/RetryableTendersDBDelegateTest.java
=> Happy path working change

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerAPIConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GlobalErrorHandler.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/exception/DuplicateFiscalCodeException.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/UserProfileService.java, src/main/resources/application.yml
https://crowncommercialservice.atlassian.net/browse/CAS-1284
=> release Fiscal code mapping code to INT

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/MessageTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/TaskEntity.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ca/TaskGroupEntity.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/TaskGroupRepo.java
=> Updated table name

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/Constants.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/AsyncPublishedStatus.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ProcurementEvent.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
https://crowncommercialservice.atlassian.net/browse/CAS-1112
=> updated dashboard status

.gitignore, .travis.yml
N/A
Fix issue with deployments to some environments not working.
This is the same as on the [frontend app](https://github.com/Crown-Commercial-Service/ccs-scale-cat-buyer-ui/pull/3723), I just did not spot it before merging
=> Fix issue with deployments to some environments not working

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/MessageController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java
=> Keeping the controller to be same as before

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/JourneysController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JourneyService.java
https://crowncommercialservice.atlassian.net/browse/CAS-1428
=> added updated api for journeys

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsController.java
https://crowncommercialservice.atlassian.net/browse/CAS-1427
=> change request body in close project

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GCloudAssessmentsController.java
[CAS-680](https://crowncommercialservice.atlassian.net/browse/CAS-680)
I have updated the spreadsheet, instead of showing just the search summary of the number of suppliers, to show the search criteria that the supplier entered.
As this data is stored as HTML, I’ve made sure that it is sanitised before being added to the CSV by adding jsoup.
[CAS-680]: https://crowncommercialservice.atlassian.net/browse/CAS-680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CAS-680 - Add search criteria to spreadsheet

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GCloudAssessmentsController.java
=> Merging the changes

iac/modules/cat-service/main.tf
https://crowncommercialservice.atlassian.net/browse/CAS-1436
=> rollbar setup for multiple envs

src/main/java/uk/gov/crowncommercial/dts/scale/cat/mapper/TimelineDependencyMapper.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/Requirement.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/TimelineDependency.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaServiceTest.java
=> Added the new timelinequestion

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
https://crowncommercialservice.atlassian.net/browse/CAS-1436
=> removed invalid logs

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/RequirementGroup.java
=> Added ignore to exclude the fields

src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java
https://crowncommercialservice.atlassian.net/browse/CAS-1436
=> removed unknown status error

src/main/java/uk/gov/crowncommercial/dts/scale/cat/mapper/TimelineDependencyMapper.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/TimelineDependency.java
=> Removed the copy values utils and built custom

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/TimelineDependency.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java
=> Update issue when timeline is null

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/CreateReplyMessage.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/MessageUpdate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/ScoringRequest.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierService.java
https://crowncommercialservice.atlassian.net/browse/CAS-1542
=> operator user changes

src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/InheritanceProcessor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/RequirementGroupAsIsProcessor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/RequirementGroupEditProcessor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/RequirementGroupPartProcessor.java
=> Copying the timelinedependency

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectServiceTest.java
https://crowncommercialservice.atlassian.net/browse/CAS-1588
=> find conclave user using sso code data

src/main/resources/application.yml
=> Updated indicator

src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/RequirementGroupPartProcessor.java
=> Corrected the merge

src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/RequirementGroupPartProcessor.java
=> Corrected the merge (#1284)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ProcurementEvent.java
https://crowncommercialservice.atlassian.net/browse/CAS-1335
Fix JSONB conversion arising from Boot upgrade
=> Fix JSONB Conversion

src/main/resources/application.yml
https://crowncommercialservice.atlassian.net/browse/CAS-1335
Change a Hibernate setting to support the lazy loading we're now doing
=> Config change to support Hibernate lazy initialization

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/Constants.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/AsyncPublishedStatus.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/entity/ProcurementEvent.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java
Reverts Crown-Commercial-Service/ccs-scale-cat-service#1212
=> Revert "updated dashboard status"

src/main/resources/sample.local-env.yml
updated the resources/sample config file
=> updated sample file

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
=> Removed Authentication

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/AbstractOcdsService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/CompiledReleaseAwardsService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/CompiledReleaseService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/CompiledReleaseTenderService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/EventStatusHelper.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/EventsHelper.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/JaggaerStatus.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/OcdsConverter.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/OcdsHelper.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/OcdsRecordMapper.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/OcdsSections.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/ProjectQuery.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/ProjectRequest.java
https://crowncommercialservice.atlassian.net/browse/CAS-1395
Tender status calculation based on Jaggaer status
=> Tender status based on local and Jaggaer status

src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/ProcurementEventRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/EventStatusHelper.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/EventSubStatus.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/EventsHelper.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/TenderSubStatus.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsCSVGenerationScheduledTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsToOpenSearchScheduledTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/TemplateDataExtractor.java
=> added location to opensearch

src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/ProcurementEventRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsCSVGenerationScheduledTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsToOpenSearchScheduledTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/TemplateDataExtractor.java
https://crowncommercialservice.atlassian.net/browse/CAS-1418
=> added order by

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerClientConfig.java
https://crowncommercialservice.atlassian.net/browse/CAS-1708
Added timeout for http client
=> Added timeout to jetty httpClient

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerClientConfig.java
=> Added timeout to jetty httpClient (#1370)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerClientConfig.java
=> Added timeout to jetty httpClient (#1370) (#1371)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerClientConfig.java
=> Added timeout to jetty httpClient (#1370) (#1371) (#1372)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
=> Update the field name

iac/modules/cat-service/main.tf, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerAPIConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerClientConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/ProcurementEventRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsCSVGenerationScheduledTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsToOpenSearchScheduledTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java, src/main/resources/application.yml
https://crowncommercialservice.atlassian.net/browse/CAS-1418
=> added batches

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/search/ProcurementEventSearch.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsToOpenSearchScheduledTask.java
=> open search index issue

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsToOpenSearchScheduledTask.java
=> deleted data in os

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/CompiledReleaseAwardsService.java
https://crowncommercialservice.atlassian.net/browse/CAS-1395
return orgmap based identifier, if supplier is not found in Conclave
=> orgmap based data, if supplier info not found in conclave

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/Application.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/SchedulerConfiguration.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsCSVGenerationScheduledTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsToOpenSearchScheduledTask.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/AssessmentsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/DocumentTemplatesControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/GCloudAssessmentsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/MessageControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersControllerTest.java
=> added scheduler lock for multiple instances

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/search/ProcurementEventSearch.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsToOpenSearchScheduledTask.java, src/main/resources/mappingfile/projectSummaryMapping.json
=> Fixed the sort order

src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/search/ProcurementEventSearch.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsToOpenSearchScheduledTask.java, src/main/resources/mappingfile/projectSummaryMapping.json
* Fixed the sort order
* Updated the scheduler data
* Updated codeclimate
* Updated the data types
---------
=> Bugfix/cas 1728 sorting order fix (#1400)

src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/ProcurementProjectRepo.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsCSVGenerationScheduledTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsToOpenSearchScheduledTask.java
https://crowncommercialservice.atlassian.net/browse/CAS-1745
=> column missing and duplicate data issue

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsCSVGenerationScheduledTask.java
https://crowncommercialservice.atlassian.net/browse/CAS-1745
=> changed csv file name

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/EventStatusHelper.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/JaggaerStatus.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsCSVGenerationScheduledTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsToOpenSearchScheduledTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/TemplateDataExtractor.java
https://crowncommercialservice.atlassian.net/browse/CAS-1748
=> update data using jaggaer data

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/EventStatusHelper.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsToOpenSearchScheduledTask.java, src/main/resources/application.yml
https://crowncommercialservice.atlassian.net/browse/CAS-1748
=> substatus change

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/TemplateDataExtractor.java
=> open for default value

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsCSVGenerationScheduledTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsToOpenSearchScheduledTask.java
=> removed broken events from DT

.codeclimate.yml
CodeClimate file is named incorrectly and improperly nested, meaning settings are not being correctly applied.  Fix it.
=> CodeClimate file is invalid - fix it

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/StatisticsService.java
https://crowncommercialservice.atlassian.net/browse/CAS-1793
=> statistics to be fetched from first published event

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/StatisticsService.java
=> merge from develop to release/int

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsCSVGenerationScheduledTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsToOpenSearchScheduledTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/TemplateDataExtractor.java
https://crowncommercialservice.atlassian.net/browse/CAS-1804
=> removed time

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/CompiledReleaseAwardsService.java
https://crowncommercialservice.atlassian.net/browse/CAS-1843
Added CAS identifier in Awarded supplier if not exist
=> added CAS Identifier in awarded supplier if not present

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsCSVGenerationScheduledTask.java
https://crowncommercialservice.atlassian.net/browse/CAS-1838
=> Data Transparency, Status open/closed discrepancy fixed

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsCSVGenerationScheduledTask.java
https://crowncommercialservice.atlassian.net/browse/CAS-1839
Status to include - open, closed, awarded, cancelled
=> Additonal project status added for CSV generation

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsCSVGenerationScheduledTask.java
https://crowncommercialservice.atlassian.net/browse/CAS-1845
SimpleQuery String based search implemented
=> simplequerystring search on opensearch database

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerClientConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/mapper/TimelineDependencyMapper.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/TimelineDependency.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsToOpenSearchScheduledTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/TemplateDataExtractor.java
=> nft uat merge conflict fix

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsCSVGenerationScheduledTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsToOpenSearchScheduledTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/TemplateDataExtractor.java
https://crowncommercialservice.atlassian.net/browse/CAS-1938
=> remove broken projects logic consolidated

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GCloudAssessmentsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java
resolve develop int merge conflict
=> resolve develop int merge conflict

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsCSVGenerationScheduledTask.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/TemplateDataExtractor.java
Reverts Crown-Commercial-Service/ccs-scale-cat-service#1482
Reverting since auto-deployment is not triggered
=> Revert "hotfix - 1938 release to production"

pom.xml, src/main/resources/application.yml
https://crowncommercialservice.atlassian.net/browse/CAS-1922
Update the PPG endpoints due to AWS migration
- `/user-profiles` to `/user-profile`
- `/organisation-profiles` to `/organisation-profile`
Import multiple swagger endpoints into the same generated model
=> CAS-1922 - Update PPG Endpoints

src/main/resources/application.yml
https://crowncommercialservice.atlassian.net/browse/CAS-1922
Update endpoint path
=> Replace user contacts endpoint path for new PPG

pom.xml
Config changes to allow the app to talk to GPaaS again.  Also, patch security issues
=> Update CAS Pre-Prod To Talk To GPaaS Properly

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java, src/main/resources/application.yml, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageServiceTest.java
https://crowncommercialservice.atlassian.net/browse/CAS-1683
Do not send broadcast messages to declined suppliers
No
=> [CAS-1683] Filter broadcast messages to declined suppliers

pom.xml
Reverts Crown-Commercial-Service/ccs-scale-cat-service#1529
Need to have Tim put this in so Travis can pick it up.
=> Revert "Hotfix Release - Resolve Tomcat Security Issues"

pom.xml
Reverts Crown-Commercial-Service/ccs-scale-cat-service#1530
=> Revert "Revert "Hotfix Release - Resolve Tomcat Security Issues""

pom.xml
Adding hotfix into develop from here:
https://github.com/Crown-Commercial-Service/ccs-scale-cat-service/pull/1521
Unable to merge directly back due to differences in develop to support PPG changes.
=> Update Tomcat to resolve security issues (putting hotfix into develop)

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/store/AbstractSupplierStore.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/store/JaggaerSupplierStore.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
https://crowncommercialservice.atlassian.net/browse/CAS-2058
Better handle where suppliers don't exist - if they don't have org mappings skip them, rather than killing the entire process
=> Non-Existing Supplier Mappings Handling

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageServiceTest.java
=> [CAS-1683] Revert broadcast messaged to declined supplier

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GlobalErrorHandler.java
https://crowncommercialservice.atlassian.net/browse/GMTRP-209
Populate detail field for API Errors
No
=> [GMTRP-209] Remove devMode to populate details field for Apierrors

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
https://crowncommercialservice.atlassian.net/browse/CAS-2005
Fixing elestic search query builder
No
=> [CAS-2005] Fix elestic search query builder

src/main/resources/application.yml
Added configuration to allow the Actuator to work correctly
=> Configuration to enable actuator to work correctly

Dockerfile
https://crowncommercialservice.atlassian.net/browse/GMTRP-273
Performs the `apk upgrade` after doing the application install, so that any packages installed are then upgraded. 
=> Fix apk upgrade, perform after install

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/UserProfileService.java
https://crowncommercialservice.atlassian.net/browse/CAS-2184
Refresh cache with SSO predicate filter
No
=> [CAS-2184] Refresh cache with  sso predicate for merged accounts

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
https://crowncommercialservice.atlassian.net/browse/CAS-2388
Add new review endpoint to service the new UI in one call what the old UI takes 50-60 to do
Old Review endpoint will be offline'd after it is phased out of the UI
=> Add Review Endpoint For UI to Consume

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java
https://crowncommercialservice.atlassian.net/browse/CAS-2393
Use Sso email to validate the user
No
=> [cas-2393] Use sso email id to validate the user

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java
https://crowncommercialservice.atlassian.net/browse/CAS-2393
Use SSO field to validate the user to retrieve sent messages.
No
=> [cas-2393] Use sso field to validate the user

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java
https://crowncommercialservice.atlassian.net/browse/CAS-2393
Use sso field to validate the user for merged accounts in case of retrieving sent emails
No
=> [cas-2393] Use sso for merged accounts to validate the user

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
https://crowncommercialservice.atlassian.net/browse/NCAS-87
Changes the number of suppliers displayed on the overview page from 0 to the relevant amount
=> NCAS 87 fix for events publishing zero suppliers

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java
https://crowncommercialservice.atlassian.net/browse/NCAS-87
Add debugging to investigate NCAS-87 
**Doesn't need reviewing or merging, simply for test**
=> add debugging for NCAS-87

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GCloudAssessmentsController.java, src/main/resources/application.yml, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/GCloudAssessmentsControllerTest.java
=> GCloud Export Framework Name Should Be Dynamic, Not Hardcoded

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GlobalErrorHandler.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/CompiledReleasePlanningService.java, src/test/resources/application-test.yml
=> Amend Budget Parsing So It Doesn't Error On Non Numeric Values

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/Constants.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/CompiledReleaseAwardsService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/CompiledReleasePlanningService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/CompiledReleaseService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/CompiledReleaseTenderService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/OcdsConverter.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/OcdsRecordMapper.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/StatisticsService.java
=> Rework Project Mapping Services To Add Error Handling and Null Checking

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/SearchRestClientConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
=> NCAS-162--Open-Search-Implementation-Update

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/SearchRestClientConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
NCAS-162
Re-implement Open Search
=> UAT Release 2.0.8

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java
=> Opportunities Number Should Be Adjusted to Remove Dupes from Total

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/SearchRestClientConfig.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EventsController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/ScoringController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierService.java
NCAS-33
Makes mapping requests async, to drastically speed them up.  Also fixes ElastiCache on local
=> Supplier Score & Response Timeouts

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/scheduler/ProjectsCSVGenerationScheduledTask.java
**NCAS-281:**
- Updates the link displayed in the opportunities download CSV file, so that they are new CaS-UI links which are valid.
=> NCAS-281--Update-opportunities-download-links-data

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java
**NCAS-160:**
- Updates the handling of dependent questions for Monetary values, as it was missing for this type of dependency.
=> NCAS-160--Fix-dependent-questions-for-monetary-values

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java
**NCAS-160:**
- Update handling for incoming Monetary input fields data, to resolve a 500 error.
=> NCAS-160--Update-Monetary-input-fields-handling

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java
NCAS-160 added to release branch 2.0.16
=> Update release branch with update

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java
Update release/2.0.16 branch with latest dev changes, around NCAS-160.
=> hotfix-release/2.0.16

src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AgreementsService.java
=> Fix AS Integration Logging

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/GlobalErrorHandler.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JourneyService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/JourneyServiceTest.java
NCAS-460
Also provide support for suppressing other Not Found errors in future if desired
=> Remove Journey Not Found Error Logging

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersController.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersControllerTest.java
=> Add new endpoint for user lookup

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/UserProfileService.java
**NCAS-442:**
- Adds ability to Link or Unlink a buyer account with an SSO.
- Handles all positive, neutral and negative journeys that can during the linking/unlinking process.
=> NCAS-442--Add-User-SSO-Linking-and-Unlinking

src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/TendersController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/jaggaer/UpdateCompanyResponse.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProfileManagementService.java
**NCAS-442 Update:**
- Fixes a conditional logic bug, where a type mismatch occurred during comparison.
- Updates response returned that is mutable, so it can be sent in the response body.
- Updates logging to be more robust and informative.
=> NCAS-442--Fix-conditional-logic-bug-and-update-response-type-returned

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/JaggaerClientConfig.java
https://crowncommercialservice.atlassian.net/browse/NCAS-537
=> NCAS 537 token null issue resolved

src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/Constants.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/config/OAuth2Config.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/EmailController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/SuppliersController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/SupplierDunsUpdate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/repo/RetryableTendersDBDelegate.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/JaggaerService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/TenderDBSupplierLinkService.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/SuppliersControllerTests.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/model/SupplierDunsUpdateTests.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/SupplierServiceTest.java
=> Add Endpoint to Allow for Supplier DUNs Updates

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/AwardController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/mapper/TimelineDependencyMapper.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/Requirement.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/helper/ProcurementEventHelperServiceImpl.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/RequirementGroupAsIsProcessor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/RequirementGroupEditProcessor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/RequirementGroupPartProcessor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/TemplateCriteriaAsIsProcessor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/TemplateCriteriaPartProcessor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/TemplateProcessor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AwardService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenValueAdaptors.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ValidationService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/CompiledReleaseTenderService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/AssessmentsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/MessageControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/AwardServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ValidationServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/util/TestUtils.java
https://crowncommercialservice.atlassian.net/browse/NCAS-458
=> upgraded openapi generator version tp 7.14.0

pom.xml, src/main/java/uk/gov/crowncommercial/dts/scale/cat/controller/AwardController.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/mapper/TimelineDependencyMapper.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/model/agreements/Requirement.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/helper/ProcurementEventHelperServiceImpl.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/RequirementGroupAsIsProcessor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/RequirementGroupEditProcessor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/RequirementGroupPartProcessor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/TemplateCriteriaAsIsProcessor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/TemplateCriteriaPartProcessor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/processors/inheritance/TemplateProcessor.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/AwardService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/DocGenValueAdaptors.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/MessageService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementProjectService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ValidationService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ca/AssessmentService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/service/ocds/CompiledReleaseTenderService.java, src/main/java/uk/gov/crowncommercial/dts/scale/cat/utils/TendersAPIModelUtils.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/AssessmentsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/MessageControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/controller/ProjectsControllerTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/AwardServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/CriteriaServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ProcurementEventServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/service/ValidationServiceTest.java, src/test/java/uk/gov/crowncommercial/dts/scale/cat/util/TestUtils.java
Reverts Crown-Commercial-Service/ccs-scale-cat-service#2175
=> Revert "upgraded openapi generator version tp 7.14.0"
